spring:  cloud:    config:      server:        git:          uri: https://github.com/NarahariP/spring-cloud-config-server  application:    name: spring-cloud-config-server    
server:  port: 8888